from pydantic import BaseModel  # Base class used to define request/response data models
from typing import List  # Used to define list fields in response models


class LoginRequest(BaseModel):  # Request body format for /login endpoint
    username: str  # Username entered by demo user
    password: str  # Password entered by demo user


class ChatRequest(BaseModel):  # Request body format for /chat endpoint
    question: str  # User's natural language question
    role: str  # User role used for RBAC filtering


class Source(BaseModel):  # Source citation format returned with RAG answers
    source_document: str  # Original document filename
    section_title: str  # Section heading where the retrieved chunk came from
    collection: str  # Document collection such as general, clinical, billing, etc.


class ChatResponse(BaseModel):  # Response body format for /chat endpoint
    answer: str  # Final answer generated by the LLM
    sources: List[Source]  # List of source citations used to answer
    retrieval_type: str  # Either hybrid_rag or sql_rag
    role: str  # Role of the user who asked the question