import sqlite3  # Connects to the local SQLite database

from langchain_groq import ChatGroq  # Uses Groq LLM to generate SQL and summarize results

from app.config import DB_PATH, GROQ_API_KEY, GROQ_MODEL  # Database and Groq settings
from app.rbac import can_use_sql  # Checks whether the role is allowed to use SQL RAG


def get_db_schema() -> str:
    """
    Read the SQLite database schema.
    This helps the LLM understand table names and column names before writing SQL.
    """

    connection = sqlite3.connect(DB_PATH)
    cursor = connection.cursor()

    cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
    tables = cursor.fetchall()

    schema_parts = []

    for table in tables:
        table_name = table[0]

        cursor.execute(f"PRAGMA table_info({table_name});")
        columns = cursor.fetchall()

        column_descriptions = []

        for column in columns:
            column_name = column[1]
            column_type = column[2]
            column_descriptions.append(f"{column_name} {column_type}")

        schema_parts.append(
            f"Table: {table_name}\nColumns: {', '.join(column_descriptions)}"
        )

    connection.close()

    return "\n\n".join(schema_parts)


def clean_sql(sql: str) -> str:
    """
    Clean SQL generated by the LLM.
    Removes markdown code fences if present.
    """

    sql = sql.strip()

    sql = sql.replace("```sql", "")
    sql = sql.replace("```", "")
    sql = sql.strip()

    return sql


def is_safe_sql(sql: str) -> bool:
    """
    Allow only SELECT queries.
    This prevents destructive SQL like DELETE, UPDATE, DROP, or INSERT.
    """

    lowered = sql.lower().strip()

    blocked_words = ["delete", "update", "drop", "insert", "alter", "create"]

    if not lowered.startswith("select"):
        return False

    for word in blocked_words:
        if word in lowered:
            return False

    return True


def generate_sql(question: str, schema: str) -> str:
    """
    Ask Groq to generate a SQLite SELECT query from the user's question.
    """

    llm = ChatGroq(
        groq_api_key=GROQ_API_KEY,
        model=GROQ_MODEL,
        temperature=0,
    )

    prompt = f"""
You are a SQLite expert.

Generate exactly one safe SQLite SELECT query for the user's question.

Rules:
- Use only the database schema provided.
- Generate SELECT queries only.
- Do not use DELETE, UPDATE, INSERT, DROP, ALTER, or CREATE.
- Return only SQL. Do not explain.

Database schema:
{schema}

User question:
{question}

SQL:
"""

    response = llm.invoke(prompt)

    return clean_sql(response.content)


def run_sql(sql: str) -> tuple[list[str], list[tuple]]:
    """
    Run a safe SQL query and return column names plus rows.
    """

    connection = sqlite3.connect(DB_PATH)
    cursor = connection.cursor()

    cursor.execute(sql)
    rows = cursor.fetchall()

    column_names = [description[0] for description in cursor.description]

    connection.close()

    return column_names, rows


def summarize_sql_result(question: str, sql: str, columns: list[str], rows: list[tuple]) -> str:
    """
    Ask Groq to summarize SQL query results in plain English.
    """

    llm = ChatGroq(
        groq_api_key=GROQ_API_KEY,
        model=GROQ_MODEL,
        temperature=0,
    )

    prompt = f"""
You are MediBot, a billing and operations assistant.

Answer the user's question based only on the SQL result.

Question:
{question}

SQL used:
{sql}

Columns:
{columns}

Rows:
{rows[:20]}

Answer:
"""

    response = llm.invoke(prompt)

    return response.content


def answer_sql_question(question: str, role: str) -> dict:
    """
    Full SQL RAG function.
    Only billing_executive and admin can use this.
    """

    if not can_use_sql(role):
        return {
            "answer": "You are not authorized to access SQL/database information.",
            "sources": [],
            "retrieval_type": "sql_blocked",
            "role": role,
        }

    schema = get_db_schema()
    sql = generate_sql(question, schema)

    if not is_safe_sql(sql):
        return {
            "answer": "The generated SQL was blocked because it was not a safe SELECT query.",
            "sources": [],
            "retrieval_type": "sql_blocked",
            "role": role,
        }

    columns, rows = run_sql(sql)

    answer = summarize_sql_result(
        question=question,
        sql=sql,
        columns=columns,
        rows=rows,
    )

    return {
        "answer": answer,
        "sources": [
            {
                "source_document": "mediassist.db",
                "section_title": "SQLite database",
                "collection": "billing",
            }
        ],
        "retrieval_type": "sql_rag",
        "role": role,
        "sql": sql,
    }


def test_sql_rag():
    """
    Test SQL RAG with an allowed role.
    """

    question = "Show me the total claim amount by status"
    role = "billing_executive"

    result = answer_sql_question(question=question, role=role)

    print("Question:", question)
    print("Role:", role)
    print("\nAnswer:")
    print(result["answer"])
    print("\nSQL:")
    print(result.get("sql"))
    print("\nRetrieval type:")
    print(result["retrieval_type"])


if __name__ == "__main__":
    test_sql_rag()